### ISSUE TITLE
i had an error when starting , on latest version of node v5.2.0

### ISSUE THREAD

**Issue by endjay** [drakerian/loopback-connector-elastic-search#10]
/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:400:20)
    at Log.listenerCount (/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:400:20)
    at Log.listenerCount (/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:400:20)
    at Log.listenerCount (/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:400:20)
    at Log.listenerCount (/Users/gusti/project/api/yummy/node_modules/loopback-connector-elastic-search/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:400:20)

**Comment by pulkitsinghal** [comment]
@endjay - try this fork/repo instead:
https://github.com/strongloop-community/loopback-connector-elastic-search

And join the community discussions at: 
https://gitter.im/strongloop-community/loopback-connector-elastic-search
