### ISSUE TITLE
the example datasource elastic-test can not be created

### ISSUE THREAD

**Issue by dishui** [drakerian/loopback-connector-elastic-search#12]
when try to run the example, I get the following error:
node .
loopback deprecated loopback.compress is deprecated. Use `require('compression');` instead. server/server.js:10:17
loopback-connector-elastic-search/examples/node_modules/loopback/lib/application.js:246
    throw err;
    ^

RangeError: Cannot create data source "elastic-test": Cannot initialize connector "elastic": Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:436:38)
    at Log.listenerCount (loopback-connector-elastic-search/examples/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:438:20)
    at Log.listenerCount (loopback-connector-elastic-search/examples/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:438:20)
    at Log.listenerCount (loopback-connector-elastic-search/examples/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:438:20)
    at Log.listenerCount (loopback-connector-elastic-search/examples/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:438:20)
    at Log.listenerCount (loopback-connector-elastic-search/examples/node_modules/elasticsearch/src/lib/log.js:68:25)

**Comment by pulkitsinghal** [comment]
@dishui - try this fork/repo instead:
https://github.com/strongloop-community/loopback-connector-elastic-search

And join the community discussions at: 
https://gitter.im/strongloop-community/loopback-connector-elastic-search
