### ISSUE TITLE
Test does not seems to run properly

### ISSUE THREAD

**Issue by smartmouse** [drakerian/loopback-connector-elastic-search#9]
When we do npm test.
There are npm ERR! Test failed.  See above for more details.

I can see that there are lots of tests defined in the test folder.
But in the package.json,  
 "scripts": {
     "test": "test"
  }

We should change it to mocha.

> loopback-connector-elastic-search@0.0.2-a test /Users/ivyho/loopback-connector-elastic-search
> mocha

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  When apply filter criteria
    ✓ should validate index and type filters 
    ✓ should validate filter criteria 

  When make id document
    ✓ should validate id created with Index filter name 

  When convert elastic result to loopback model
    ✓ should run convert function 
    ✓ should validate matched fields 
    ✓ should validate data types 

  When set elastic client options
    ✓ should return number for defaultSize option 
    ✓ should return string type for searchIndex and searchType 
    ✓ should return a valid URL for elastic client 

  9 passing (19ms)

**Comment by pulkitsinghal** [comment]
@smartmouse - may i suggest you use a slightly more active/up-2-date/current/official~ish fork instead?

Here: https://github.com/strongloop-community/loopback-connector-elastic-search

**Comment by smartmouse** [comment]
Sure, Thanks for the link and pointer.
When I run test on windows/Mac. it shows some errors though. Do you know if there are any special set up for running the tests?
Looks like there are some failure with the tests.

C:\Users\IBM_ADMIN\loopback-connector-elastic-search>npm test

> loopback-connector-es@1.0.2 test C:\Users\IBM_ADMIN\loopback-connector-elastic
-search
> test

'test' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

C:\Users\IBM_ADMIN\loopback-connector-elastic-search>npm test

> loopback-connector-es@1.0.2 test C:\Users\IBM_ADMIN\loopback-connector-elastic
-search
> mocha

child_process: customFds option is deprecated, use stdio instead.


  Connector

        customSettings will override global settings for datasource

    √ should configure defaults when building filters
will sort on _uid by default when IDs are auto-generated by elasticsearch
    1) should build a query for the WHERE filter
will sort on _uid by default when IDs are auto-generated by elasticsearch
    √ should use a NATIVE filter query as-is

  basic-querying

        will use global settings for datasource

Elasticsearch INFO: 2015-11-21T05:19:10Z
  Adding connection to https://hosted.foundcluster.com:9243/

Elasticsearch DEBUG: 2015-11-21T05:19:10Z
  starting request { method: 'HEAD',
    castExists: true,
    path: '/shakespeare',
    query: {} }


Elasticsearch ERROR: 2015-11-21T05:19:10Z
  Error: Request error, retrying -- getaddrinfo ENOTFOUND hosted.foundcluster.co
m
      at Log.error (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_mo
dules\elasticsearch\src\lib\log.js:218:60)
      at checkRespForFailure (C:\Users\IBM_ADMIN\loopback-connector-elastic-sear
ch\node_modules\elasticsearch\src\lib\transport.js:211:18)
      at HttpConnector.<anonymous> (C:\Users\IBM_ADMIN\loopback-connector-elasti
c-search\node_modules\elasticsearch\src\lib\connectors\http.js:153:7)
      at ClientRequest.wrapper (C:\Users\IBM_ADMIN\loopback-connector-elastic-se
arch\node_modules\lodash\index.js:3095:19)
      at ClientRequest.emit (events.js:107:17)
      at TLSSocket.socketErrorListener (_http_client.js:271:9)
      at TLSSocket.emit (events.js:129:20)
      at net.js:950:16
      at process._tickCallback (node.js:355:11)

Connection fails:  { [Error: No Living connections]
  message: 'No Living connections',
  body: false,
  status: undefined }
It will be retried for the next request.
Unhandled rejection Error: No Living connections
    at sendReqWithConnection (C:\Users\IBM_ADMIN\loopback-connector-elastic-sear
ch\node_modules\elasticsearch\src\lib\transport.js:190:15)
    at next (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules\e
lasticsearch\src\lib\connection_pool.js:213:7)
    at process._tickCallback (node.js:355:11)
Elasticsearch TRACE: 2015-11-21T05:19:10Z
  -> HEAD https://hosted.foundcluster.com:9243/shakespeare

  <- 0


Elasticsearch ERROR: 2015-11-21T05:19:10Z
  Error: Request error, retrying -- getaddrinfo ENOTFOUND hosted.foundcluster.co
m
      at Log.error (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_mo
dules\elasticsearch\src\lib\log.js:218:60)
      at checkRespForFailure (C:\Users\IBM_ADMIN\loopback-connector-elastic-sear
ch\node_modules\elasticsearch\src\lib\transport.js:211:18)
      at HttpConnector.<anonymous> (C:\Users\IBM_ADMIN\loopback-connector-elasti
c-search\node_modules\elasticsearch\src\lib\connectors\http.js:153:7)
      at ClientRequest.wrapper (C:\Users\IBM_ADMIN\loopback-connector-elastic-se
arch\node_modules\lodash\index.js:3095:19)
      at ClientRequest.emit (events.js:107:17)
      at TLSSocket.socketErrorListener (_http_client.js:271:9)
      at TLSSocket.emit (events.js:129:20)
      at net.js:950:16
      at process._tickCallback (node.js:355:11)

Elasticsearch TRACE: 2015-11-21T05:19:11Z
  -> HEAD https://hosted.foundcluster.com:9243/

  <- 0


Elasticsearch WARNING: 2015-11-21T05:19:11Z
  Unable to revive connection: https://hosted.foundcluster.com:9243/

Elasticsearch WARNING: 2015-11-21T05:19:11Z
  No living connections

Connection fails:  { [Error: No Living connections]
  message: 'No Living connections',
  body: false,
  status: undefined }
It will be retried for the next request.
Unhandled rejection Error: No Living connections
    at sendReqWithConnection (C:\Users\IBM_ADMIN\loopback-connector-elastic-sear
ch\node_modules\elasticsearch\src\lib\transport.js:190:15)
    at next (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules\e
lasticsearch\src\lib\connection_pool.js:213:7)
    at process._tickCallback (node.js:355:11)
Elasticsearch DEBUG: 2015-11-21T05:19:12Z
  starting request { method: 'DELETE', path: '/shakespeare', query: {} }


Elasticsearch TRACE: 2015-11-21T05:19:12Z
  -> HEAD https://hosted.foundcluster.com:9243/

  <- 0


Elasticsearch WARNING: 2015-11-21T05:19:12Z
  Unable to revive connection: https://hosted.foundcluster.com:9243/

Elasticsearch WARNING: 2015-11-21T05:19:12Z
  No living connections

    2) "before all" hook


  2 passing (3s)
  2 failing

  1) Connector should build a query for the WHERE filter:

      AssertionError: expected { Object (sort, query) } to deeply equal { Object
 (sort, query) }
      + expected - actual

             ]
           }
         }
         "sort": [
      +    "id"
      -    "_uid"
         ]
       }

      at Assertion.assertEqual (C:\Users\IBM_ADMIN\loopback-connector-elastic-se
arch\node_modules\chai\lib\chai\core\assertions.js:439:19)
      at Assertion.ctx.(anonymous function) [as equals] (C:\Users\IBM_ADMIN\loop
back-connector-elastic-search\node_modules\chai\lib\chai\utils\addMethod.js:40:2
5)
      at Context.<anonymous> (C:\Users\IBM_ADMIN\loopback-connector-elastic-sear
ch\test\01.filters.test.js:47:24)
      at Test.Runnable.run (C:\Users\IBM_ADMIN\loopback-connector-elastic-search
\node_modules\mocha\lib\runnable.js:217:15)
      at Runner.runTest (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\no
de_modules\mocha\lib\runner.js:373:10)
      at C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules\mocha
\lib\runner.js:451:12
      at next (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules
\mocha\lib\runner.js:298:14)
      at C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules\mocha
\lib\runner.js:308:7
      at next (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules
\mocha\lib\runner.js:246:23)
      at Immediate._onImmediate (C:\Users\IBM_ADMIN\loopback-connector-elastic-s
earch\node_modules\mocha\lib\runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:367:17)

  2) basic-querying "before all" hook:
     Error: No Living connections
      at sendReqWithConnection (C:\Users\IBM_ADMIN\loopback-connector-elastic-se
arch\node_modules\elasticsearch\src\lib\transport.js:190:15)
      at next (C:\Users\IBM_ADMIN\loopback-connector-elastic-search\node_modules
\elasticsearch\src\lib\connection_pool.js:213:7)
      at process._tickCallback (node.js:355:11)



npm ERR! Test failed.  See above for more details.

C:\Users\IBM_ADMIN\loopback-connector-elastic-search>

**Comment by smartmouse** [comment]
sure. Thank you for the pointer.
There are some failure in the new tests, though. Not sure if there are any setup required.

https://gist.github.com/smartmouse/36e6e122d1f3d82d5fc5

**Comment by pulkitsinghal** [comment]
@smartmouse - yes to test you need to point at an ES server, please refer to the readme in the repo mentioned above, it should talk about this and if it doesn't then open an issue describing what's missing or confusing in that repo's readme

Also use the gitter.im chat room of that repo to get help quicker
